title: Ty's Super Site
author: Ty Burningham
logo: /assets/img/me_n_waldo.jpg
google_analytics:
theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one